apiVersion: v1
kind: ServiceAccount
metadata:
  name: "{{ .Values.serviceAccount.name }}"
  labels:
    app.kubernetes.io/name: provio
    app.kubernetes.io/instance: "{{ .Release.Name }}"
  annotations: {}
