//! Codegen: translate the native provio.yaml IR (`provio_policy::policy_file`)
//! into Cedar policy text (spec §7, Contract 2).
//!
//! The translation is pure and runs entirely at `from_source`/`reload` time;
//! evaluation only builds the Cedar request context from the call.
//!
//! Shape of the generated policy set:
//!
//! - one `permit(principal, action, resource) when { ... };` policy per
//!   provio rule, with policy id `r<index>` (source order) and a
//!   `@provio_rule("<id>")` annotation. A satisfied policy means "this rule's
//!   `when` matched"; the host picks the lowest satisfied index, which is
//!   the native first-match-wins order.
//! - `and`/`or`/`not` map to `&&`/`||`/`!` (Cedar short-circuits, like the
//!   native evaluator).
//! - `==`/`!=` map to the same operators; `startswith`/`endswith`/`contains`
//!   map to `like "w*"` / `like "*w"` / `like "*w*"` with `*` in the operand
//!   escaped as `\*`.
//! - `matches` has no Cedar equivalent (Cedar has no regex). Each `matches`
//!   predicate gets a slot `k` and compiles to `context.re.m<k>`, a boolean
//!   the host precomputes with the very `regex::Regex` the native engine
//!   compiled (see [`RegexSlot`]).
//! - `in <list>` becomes a disjunction over the entries. Plain entries are
//!   exact `==`; `*.base` wildcard entries compare against `context.lc.<f>`
//!   (the host-provided ASCII-lowercased value — Cedar has no `lower()`),
//!   as `== "base" || like "*.base"`: the native dot-boundary matcher.
//! - Optional context fields are only present in the context record when
//!   set, and every predicate over one is guarded by `context has <f>`, so
//!   an absent field never matches and never errors — including under `!`,
//!   exactly as natively. Unknown DSL fields and empty lists compile to
//!   `false`.

use provio_policy::ast::{Expr, Field, Op, Predicate};
use provio_policy::policy_file::CompiledPolicy;
use regex::Regex;

/// A host-evaluated `matches` predicate: slot `k` is exposed to Cedar as
/// the boolean `context.re.m<k>`.
#[derive(Debug, Clone)]
pub(crate) struct RegexSlot {
    pub(crate) field: Field,
    pub(crate) regex: Regex,
}

/// The generated Cedar policies (one per provio rule, in source order) and
/// the host-evaluated regex slots they reference.
#[derive(Debug, Clone)]
pub(crate) struct Generated {
    /// Cedar source text for rule `i`, to be parsed with policy id `r<i>`.
    pub(crate) policies: Vec<String>,
    pub(crate) regex_slots: Vec<RegexSlot>,
}

/// Cedar policy id for the rule at `index`.
pub(crate) fn policy_id(index: usize) -> String {
    format!("r{}", index)
}

/// Inverse of [`policy_id`]; `None` for anything this codegen did not emit.
pub(crate) fn rule_index(policy_id: &str) -> Option<usize> {
    let digits = policy_id.strip_prefix('r')?;
    if digits.is_empty() || !digits.bytes().all(|b| b.is_ascii_digit()) {
        return None;
    }
    digits.parse().ok()
}

/// Generate the Cedar policies for a compiled policy.
pub(crate) fn generate(policy: &CompiledPolicy) -> Generated {
    let mut cg = Codegen {
        regex_slots: Vec::new(),
    };
    let policies = policy
        .rules
        .iter()
        .map(|rule| {
            let cond = cg.expr(&rule.when);
            let location = match (&rule.pack, rule.line) {
                (Some(pack), _) => format!(" (pack:{})", pack),
                (None, Some(line)) => format!(" (provio.yaml:{})", line),
                (None, None) => String::new(),
            };
            format!(
                "// Generated by provio-policy-cedar from provio.yaml{} — do not edit by hand.\n\
                 @provio_rule({})\n\
                 permit(principal, action, resource)\nwhen {{ {} }};\n",
                location,
                cedar_string(&rule.id),
                cond
            )
        })
        .collect();
    Generated {
        policies,
        regex_slots: cg.regex_slots,
    }
}

struct Codegen {
    regex_slots: Vec<RegexSlot>,
}

impl Codegen {
    fn expr(&mut self, expr: &Expr) -> String {
        match expr {
            Expr::Or(a, b) => format!("({} || {})", self.expr(a), self.expr(b)),
            Expr::And(a, b) => format!("({} && {})", self.expr(a), self.expr(b)),
            // Always parenthesised: Cedar caps chained unary `!` at four.
            Expr::Not(inner) => format!("!({})", self.expr(inner)),
            Expr::Pred(p) => self.pred(p),
        }
    }

    fn pred(&mut self, pred: &Predicate) -> String {
        match pred {
            Predicate::Compare { field, op } => {
                let Some(name) = field_name(*field) else {
                    // Unknown DSL identifiers never match (native: None).
                    return "false".to_string();
                };
                let f = format!("context.{}", name);
                let test = match op {
                    Op::Eq(w) => format!("{} == {}", f, cedar_string(w)),
                    Op::Ne(w) => format!("{} != {}", f, cedar_string(w)),
                    Op::StartsWith(w) => format!("{} like {}", f, like_pattern("", w, "*")),
                    Op::EndsWith(w) => format!("{} like {}", f, like_pattern("*", w, "")),
                    Op::Contains(w) => format!("{} like {}", f, like_pattern("*", w, "*")),
                    Op::Matches(re) => {
                        let k = self.regex_slots.len();
                        self.regex_slots.push(RegexSlot {
                            field: *field,
                            regex: re.clone(),
                        });
                        // The host computes this false for an absent field,
                        // so no `has` guard is needed (it is always set).
                        return format!("context.re.m{}", k);
                    }
                };
                guard(*field, name, test)
            }
            Predicate::In { field, list } => {
                let Some(name) = field_name(*field) else {
                    return "false".to_string();
                };
                if list.is_empty() {
                    return "false".to_string();
                }
                let terms: Vec<String> = list
                    .iter()
                    .map(|entry| match entry.strip_prefix("*.") {
                        Some(base) => {
                            let lowered = base.to_ascii_lowercase();
                            format!(
                                "context.lc.{n} == {} || context.lc.{n} like {}",
                                cedar_string(&lowered),
                                like_pattern("*.", &lowered, ""),
                                n = name
                            )
                        }
                        None => format!("context.{} == {}", name, cedar_string(entry)),
                    })
                    .collect();
                guard(*field, name, terms.join(" || "))
            }
        }
    }
}

/// Wrap `test` in a `context has <field>` guard for optional fields, so an
/// absent field is a non-match (never an evaluation error).
fn guard(field: Field, name: &str, test: String) -> String {
    if is_always_present(field) {
        format!("({})", test)
    } else {
        format!("(context has {} && ({}))", name, test)
    }
}

/// Fields `ToolCallContext` always carries (non-`Option`).
fn is_always_present(field: Field) -> bool {
    matches!(field, Field::Tool | Field::Agent | Field::Mode)
}

/// The context attribute holding a DSL field; `None` for unknown fields.
pub(crate) fn field_name(field: Field) -> Option<&'static str> {
    Some(match field {
        Field::Tool => "tool",
        Field::Command => "command",
        Field::Path => "path",
        Field::UrlHost => "url_host",
        Field::Query => "query",
        Field::Agent => "agent",
        Field::Mode => "mode",
        Field::Server => "server",
        Field::Trust => "trust",
        Field::Unknown => return None,
    })
}

/// A Cedar string literal. Cedar uses Rust-style escapes; backslash, quote
/// and every control character are escaped, other text passes as UTF-8.
pub(crate) fn cedar_string(s: &str) -> String {
    let mut out = String::with_capacity(s.len() + 2);
    out.push('"');
    push_escaped(&mut out, s, false);
    out.push('"');
    out
}

/// A Cedar `like` pattern literal: `prefix` and `suffix` are raw pattern
/// text (wildcards), `literal` is matched verbatim (`*` escaped as `\*`).
fn like_pattern(prefix: &str, literal: &str, suffix: &str) -> String {
    let mut out = String::with_capacity(literal.len() + 4);
    out.push('"');
    out.push_str(prefix);
    push_escaped(&mut out, literal, true);
    out.push_str(suffix);
    out.push('"');
    out
}

fn push_escaped(out: &mut String, s: &str, escape_star: bool) {
    for c in s.chars() {
        match c {
            '\\' => out.push_str("\\\\"),
            '"' => out.push_str("\\\""),
            '*' if escape_star => out.push_str("\\*"),
            c if c.is_control() => out.push_str(&format!("\\u{{{:x}}}", c as u32)),
            c => out.push(c),
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use provio_policy::policy_file::compile;

    fn gen(src: &str) -> Generated {
        let policy = compile(src).unwrap_or_else(|e| panic!("policy should compile: {}", e));
        generate(&policy)
    }

    #[test]
    fn cedar_string_escapes_literals() {
        assert_eq!(cedar_string("plain"), "\"plain\"");
        assert_eq!(cedar_string("a\"b"), "\"a\\\"b\"");
        assert_eq!(cedar_string("a\\b"), "\"a\\\\b\"");
        assert_eq!(cedar_string("a\nb\tc"), "\"a\\u{a}b\\u{9}c\"");
        assert_eq!(cedar_string("a*b"), "\"a*b\"");
        assert_eq!(cedar_string("\u{1}"), "\"\\u{1}\"");
    }

    #[test]
    fn like_pattern_escapes_star() {
        assert_eq!(like_pattern("", "a*b", "*"), "\"a\\*b*\"");
        assert_eq!(like_pattern("*", "x\\y", ""), "\"*x\\\\y\"");
    }

    #[test]
    fn policy_ids_round_trip() {
        for i in [0usize, 1, 9, 10, 12345] {
            assert_eq!(rule_index(&policy_id(i)), Some(i));
        }
        for bad in ["", "r", "x1", "r-1", "r1a", "policy0", "r+1"] {
            assert_eq!(rule_index(bad), None, "{:?}", bad);
        }
    }

    #[test]
    fn shape_for_simple_policy() {
        let g = gen(r#"version: 1
default: deny
rules:
  - id: bash-only
    when: tool == "bash"
    verdict: allow
"#);
        assert_eq!(g.policies.len(), 1);
        assert!(g.regex_slots.is_empty());
        let p = &g.policies[0];
        assert!(p.contains("@provio_rule(\"bash-only\")"));
        assert!(p.contains("(provio.yaml:4)"));
        assert!(p.contains("permit(principal, action, resource)"));
        assert!(p.contains("when { (context.tool == \"bash\") };"));
    }

    #[test]
    fn translate_ops_not_in_and_regex_slots() {
        let g = gen(r#"version: 1
default: ask
rules:
  - id: egress
    when: tool == "http" and not url.host in hosts.allowed
    verdict: deny
    reason: "off-list"
  - id: shell
    when: command startswith "rm" or command matches "mkfs" or path endswith ".pem" or query contains "*"
    verdict: deny
  - id: mystery
    when: nosuchfield == "x"
    verdict: deny
hosts:
  allowed: [api.github.com, "*.internal.acme.com"]
"#);
        let egress = &g.policies[0];
        assert!(egress.contains("(context.tool == \"http\") && !((context has url_host && ("));
        assert!(egress.contains("context.url_host == \"api.github.com\""));
        assert!(egress.contains("context.lc.url_host == \"internal.acme.com\""));
        assert!(egress.contains("context.lc.url_host like \"*.internal.acme.com\""));

        let shell = &g.policies[1];
        assert!(shell.contains("(context has command && (context.command like \"rm*\"))"));
        assert!(shell.contains("context.re.m0"));
        assert!(shell.contains("(context has path && (context.path like \"*.pem\"))"));
        assert!(shell.contains("(context has query && (context.query like \"*\\**\"))"));
        assert_eq!(g.regex_slots.len(), 1);
        assert_eq!(g.regex_slots[0].field, Field::Command);
        assert_eq!(g.regex_slots[0].regex.as_str(), "mkfs");

        assert!(g.policies[2].contains("when { false };"));
    }

    #[test]
    fn empty_policy_generates_nothing() {
        let g = gen("version: 1\ndefault: allow\n");
        assert!(g.policies.is_empty());
        assert!(g.regex_slots.is_empty());
    }
}
