//! Codegen: translate the native provio.yaml IR (`provio_policy::policy_file`)
//! into a Rego module evaluated by regorus (spec §7, Contract 2).
//!
//! The translation is pure and runs entirely at `from_source`/`reload` time;
//! evaluation only feeds the call context as the Rego `input` document.
//!
//! Shape of the generated module (one package `provio`):
//!
//! - one matcher rule `w0..wN` per policy rule, in source order. `and`
//!   becomes body sequencing, `or` becomes additional bodies of the same
//!   matcher, `not X` becomes `not cN` where `cN` is a generated helper rule
//!   holding X's disjunction.
//! - `data.provio.decision` is an `else` chain over the matchers that yields
//!   the first matching rule's index, or `"default"` when nothing matches.
//!   The Rust host turns the index into the canonical verdict, so Deny/Ask
//!   carry rule_id, reason and `provio.yaml:LINE` exactly like the native
//!   engine (spec §12).
//!
//! Field semantics come for free from Rego's undefinedness: absent context
//! fields are omitted from `input`, so their references are undefined and
//! every predicate over them fails — the native engine's "absent field never
//! matches" rule, including under `not` (`not x == "v"` is true when `x` is
//! absent, as it is natively).

use provio_policy::ast::{Expr, Field, Op, Predicate};
use provio_policy::policy_file::CompiledPolicy;

/// Package of the generated module. Evaluate `data.provio.decision`.
pub(crate) const PACKAGE: &str = "provio";

/// Generate the Rego module for a compiled policy.
pub(crate) fn generate_module(policy: &CompiledPolicy) -> String {
    let mut cg = Codegen {
        helpers: Vec::new(),
    };

    let mut out = String::new();
    out.push_str("# Generated by provio-policy-rego from provio.yaml — do not edit by hand.\n");
    out.push_str(&format!(
        "# Policy version {}, default verdict {:?}, {} rules. First match wins;\n",
        policy.version,
        policy.default,
        policy.rules.len()
    ));
    out.push_str("# unmatched calls fall through to decision == \"default\" (the host applies\n");
    out.push_str("# the policy default verdict).\n");
    out.push_str(&format!("package {}\n\n", PACKAGE));

    for (i, rule) in policy.rules.iter().enumerate() {
        out.push_str(&format!(
            "# rule {}: {}{}\n",
            i,
            comment_text(&rule.id),
            match rule.line {
                Some(line) => format!(" (provio.yaml:{})", line),
                None => String::new(),
            }
        ));
        for body in cg.bodies(&rule.when) {
            out.push_str(&rule_def(&format!("w{}", i), &body));
        }
        out.push('\n');
    }

    // First-match-wins: an else chain preserves source order.
    let mut decision = String::new();
    for i in 0..policy.rules.len() {
        let keyword = if i == 0 { "decision :=" } else { "else :=" };
        decision.push_str(&format!("{} \"{}\" if {{ w{} }} ", keyword, i, i));
    }
    if policy.rules.is_empty() {
        decision.push_str("decision := \"default\"");
    } else {
        decision.push_str("else := \"default\"");
    }
    out.push_str(decision.trim_end());
    out.push('\n');

    // Helpers are emitted after the matchers for readability; Rego rule
    // order does not matter.
    out.push_str(&cg.helpers.concat());

    out
}

/// One generated helper-rule namespace for `not` operands.
struct Codegen {
    helpers: Vec<String>,
}

impl Codegen {
    /// Compile an expression into a set of Rego rule bodies (each body is a
    /// conjunction of expression lines; the set is the disjunction). An empty
    /// set means "never matches" and cannot occur: every leaf produces at
    /// least one body.
    fn bodies(&mut self, expr: &Expr) -> Vec<Vec<String>> {
        match expr {
            Expr::Or(a, b) => {
                let mut all = self.bodies(a);
                all.extend(self.bodies(b));
                all
            }
            Expr::And(a, b) => {
                // Cross product of bodies; either side empty -> never matches.
                let mut out = Vec::new();
                for a_body in self.bodies(a) {
                    for b_body in self.bodies(b) {
                        let mut body = a_body.clone();
                        body.extend(b_body);
                        out.push(body);
                    }
                }
                out
            }
            Expr::Not(inner) => {
                let name = format!("c{}", self.helpers.len());
                for body in self.bodies(inner) {
                    self.helpers.push(rule_def(&name, &body));
                }
                // `not cN` is true exactly when no body of cN holds — which
                // is also the case when cN's field references are undefined,
                // matching the native engine's `not` over absent fields.
                vec![vec![format!("not {}", name)]]
            }
            Expr::Pred(p) => match p {
                Predicate::Compare { field, op } => vec![vec![compare_line(*field, op)]],
                Predicate::In { field, list } => {
                    if list.is_empty() {
                        return vec![vec!["false".to_string()]];
                    }
                    list.iter()
                        .flat_map(|entry| entry_bodies(*field, entry))
                        .map(|line| vec![line])
                        .collect()
                }
            },
        }
    }
}

/// A comparison predicate as one Rego expression line. Absent fields make
/// the reference undefined, failing the body — native `eval_pred` returns
/// false for every operator over `None`, the same outcome.
fn compare_line(field: Field, op: &Op) -> String {
    match field {
        // Unknown DSL identifiers never match (native: field_value -> None).
        Field::Unknown => "false".to_string(),
        _ => {
            let f = field_ref(field);
            match op {
                Op::Eq(w) => format!("{} == {}", f, rego_string(w)),
                Op::Ne(w) => format!("{} != {}", f, rego_string(w)),
                Op::StartsWith(w) => format!("startswith({}, {})", f, rego_string(w)),
                Op::EndsWith(w) => format!("endswith({}, {})", f, rego_string(w)),
                Op::Contains(w) => format!("contains({}, {})", f, rego_string(w)),
                // regorus implements regex.match with the same Rust `regex`
                // crate and unanchored `is_match` as the native engine.
                Op::Matches(re) => format!("regex.match({}, {})", rego_string(re.as_str()), f),
            }
        }
    }
}

/// List membership as one body per entry. Plain entries match exactly;
/// `*.base.tld` wildcard entries match case-insensitively on a dot boundary
/// (native `list_entry_matches`). Only relevant for the always-defined
/// `url_host` case in practice.
fn entry_bodies(field: Field, entry: &str) -> Vec<String> {
    match entry.strip_prefix("*.") {
        Some(base) => {
            let f = field_ref(field);
            let lowered = base.to_ascii_lowercase();
            vec![
                format!("lower({}) == {}", f, rego_string(&lowered)),
                format!(
                    "endswith(lower({}), {})",
                    f,
                    rego_string(&format!(".{}", lowered))
                ),
            ]
        }
        None => vec![format!("{} == {}", field_ref(field), rego_string(entry))],
    }
}

/// The `input` key holding a DSL field. Absent context fields are simply
/// not present in the object, so these references are undefined then.
fn field_ref(field: Field) -> &'static str {
    match field {
        Field::Tool => "input.tool",
        Field::Command => "input.command",
        Field::Path => "input.path",
        Field::UrlHost => "input.url_host",
        Field::Query => "input.query",
        Field::Agent => "input.agent",
        Field::Mode => "input.mode",
        Field::Server => "input.server",
        Field::Trust => "input.trust",
        Field::Unknown => unreachable!("compare_line handles Unknown before this"),
    }
}

/// A boolean rule definition in Rego v1 syntax with tab indentation.
fn rule_def(name: &str, body: &[String]) -> String {
    let mut out = format!("{} if {{\n", name);
    for line in body {
        out.push_str(&format!("\t{}\n", line));
    }
    out.push_str("}\n");
    out
}

/// A Rego string literal: Rego uses Go-style escapes; the only characters
/// that need attention are backslash, quote, and control characters
/// (non-ASCII text passes through as UTF-8).
pub(crate) fn rego_string(s: &str) -> String {
    let mut out = String::with_capacity(s.len() + 2);
    out.push('"');
    for c in s.chars() {
        match c {
            '\\' => out.push_str("\\\\"),
            '"' => out.push_str("\\\""),
            '\n' => out.push_str("\\n"),
            '\r' => out.push_str("\\r"),
            '\t' => out.push_str("\\t"),
            c if (c as u32) < 0x20 => {
                out.push_str(&format!("\\u{:04x}", c as u32));
            }
            c => out.push(c),
        }
    }
    out.push('"');
    out
}

/// Make rule text safe to embed in a `#` comment (no line breaks, bounded).
fn comment_text(s: &str) -> String {
    let one_line = s.replace(['\n', '\r'], " ");
    one_line.chars().take(120).collect()
}

#[cfg(test)]
mod tests {
    use super::*;
    use provio_core::verdict::DefaultVerdict;
    use provio_policy::policy_file::compile;

    fn module(src: &str) -> String {
        let policy = compile(src).unwrap_or_else(|e| panic!("policy should compile: {}", e));
        generate_module(&policy)
    }

    #[test]
    fn rego_string_escapes_literals() {
        assert_eq!(rego_string("plain"), "\"plain\"");
        assert_eq!(rego_string("a\"b"), "\"a\\\"b\"");
        assert_eq!(rego_string("a\\b"), "\"a\\\\b\"");
        assert_eq!(rego_string("a\nb\tc"), "\"a\\nb\\tc\"");
        // Regex patterns keep their backslashes as literal data.
        assert_eq!(rego_string("\\.env|id_rsa"), "\"\\\\.env|id_rsa\"");
        assert_eq!(rego_string("\u{1}"), "\"\\u0001\"");
    }

    #[test]
    fn module_shape_for_simple_policy() {
        let m = module(
            r#"version: 1
default: deny
rules:
  - id: bash-only
    when: tool == "bash"
    verdict: allow
"#,
        );
        assert!(m.starts_with("# Generated by provio-policy-rego"));
        assert!(m.contains("package provio"));
        assert!(m.contains("w0 if {"));
        assert!(m.contains("\tinput.tool == \"bash\"\n"));
        assert!(m.contains("decision := \"0\" if { w0 } else := \"default\""));
        // No helpers without `not`.
        assert!(!m.contains("c0 if {"));
    }

    #[test]
    fn module_translate_or_and_not_and_in() {
        let m = module(
            r#"version: 1
default: ask
rules:
  - id: egress
    when: tool == "http" and not url.host in hosts.allowed
    verdict: deny
    reason: "off-list"
hosts:
  allowed: [api.github.com, "*.internal.acme.com"]
"#,
        );
        // `in` expands to one body per entry, wildcard on a dot boundary.
        assert!(m.contains("\tinput.url_host == \"api.github.com\"\n"));
        assert!(m.contains("\tlower(input.url_host) == \"internal.acme.com\"\n"));
        assert!(m.contains("\tendswith(lower(input.url_host), \".internal.acme.com\")\n"));
        // `not` lowers into a generated helper rule.
        assert!(m.contains("not c0"));
        assert!(m.contains("c0 if {"));
        // `and` sequences inside one body.
        assert!(m.contains("\tinput.tool == \"http\"\n\tnot c0\n"));
        // Wildcard expansion uses the `endswith` builtin.
        assert!(m.contains("endswith(lower(input.url_host)"));
    }

    #[test]
    fn unknown_field_never_matches() {
        let m = module(
            r#"version: 1
default: ask
rules:
  - id: mystery
    when: nosuchfield == "x"
    verdict: deny
"#,
        );
        assert!(m.contains("\tfalse\n"));
    }

    #[test]
    fn empty_rules_default_decision() {
        let m = module("version: 1\ndefault: allow\n");
        assert!(m.contains("decision := \"default\""));
        assert!(!m.contains("w0"));
        assert_eq!(compile_policy_default(), DefaultVerdict::Allow);
    }

    fn compile_policy_default() -> DefaultVerdict {
        compile("version: 1\ndefault: allow\n").unwrap().default
    }
}
