#!/usr/bin/env bash
# Build the in-browser playground's WebAssembly (crates/provio-wasm) and write
# commit-ready artifacts to site/assets/playground/:
#
#   provio_wasm_bg.wasm  the provio policy engine + ledger record format
#   provio_wasm.js       wasm-bindgen `--target web` glue (ES module)
#   presets.js         examples/*.yaml, packs/*/pack.yaml and the simulator
#                      presets (crates/provio-wasm/presets/calls.json), baked in
#
# The site has no build step, so these files are committed. CI re-runs this
# script and fails if the output differs, so the build is pinned:
#
#   - Rust toolchain  $PLAYGROUND_TOOLCHAIN (default below), wasm32 target;
#   - wasm-bindgen-cli exactly the version provio-wasm pins in its Cargo.toml;
#   - size profile passed with --config (opt-level=z, panic=abort) so the
#     workspace's own release profile is untouched;
#   - --remap-path-prefix so no host path (CARGO_HOME, checkout dir) ends up
#     in the binary: the output is identical on any Linux machine.
#
# Build on Linux (CI, or WSL on Windows): a Windows host embeds backslash
# paths and produces different bytes.
#
# Usage: scripts/build_playground.sh           # build + write artifacts
#        scripts/build_playground.sh --check   # build, then fail on any diff
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$ROOT"

TOOLCHAIN="${PLAYGROUND_TOOLCHAIN:-1.98.1}"
OUT="site/assets/playground"
export CARGO_TARGET_DIR="${CARGO_TARGET_DIR:-target/agent-wasm}"
CHECK=0
[[ "${1:-}" == "--check" ]] && CHECK=1

die() { echo "build_playground: $*" >&2; exit 1; }

# --- tool checks -----------------------------------------------------------
BINDGEN_VERSION="$(sed -n 's/^wasm-bindgen = "=\([0-9.]*\)"/\1/p' crates/provio-wasm/Cargo.toml)"
[[ -n "$BINDGEN_VERSION" ]] || die "could not read the pinned wasm-bindgen version from crates/provio-wasm/Cargo.toml"
command -v wasm-bindgen >/dev/null \
  || die "wasm-bindgen not found; run: cargo install wasm-bindgen-cli --version $BINDGEN_VERSION --locked"
HAVE="$(wasm-bindgen --version | awk '{print $2}')"
[[ "$HAVE" == "$BINDGEN_VERSION" ]] \
  || die "wasm-bindgen $HAVE installed, provio-wasm pins $BINDGEN_VERSION; run: cargo install wasm-bindgen-cli --version $BINDGEN_VERSION --locked --force"
command -v python3 >/dev/null || die "python3 not found (needed to bake presets.js)"

CARGO=(cargo)
if command -v rustup >/dev/null; then
  rustup toolchain list | grep -q "^$TOOLCHAIN" \
    || rustup toolchain install "$TOOLCHAIN" --profile minimal --target wasm32-unknown-unknown
  rustup target list --installed --toolchain "$TOOLCHAIN" | grep -q '^wasm32-unknown-unknown$' \
    || rustup target add wasm32-unknown-unknown --toolchain "$TOOLCHAIN"
  CARGO=(cargo "+$TOOLCHAIN")
fi

# --- wasm ------------------------------------------------------------------
CARGO_HOME_DIR="${CARGO_HOME:-$HOME/.cargo}"
export RUSTFLAGS="--remap-path-prefix=$CARGO_HOME_DIR=/cargo --remap-path-prefix=$ROOT=/provio"
"${CARGO[@]}" build --locked -p provio-wasm --release --target wasm32-unknown-unknown \
  --config 'profile.release.opt-level="z"' \
  --config 'profile.release.panic="abort"'

STAGE="$(mktemp -d)"
trap 'rm -rf "$STAGE"' EXIT
wasm-bindgen --target web --no-typescript --out-dir "$STAGE" \
  "$CARGO_TARGET_DIR/wasm32-unknown-unknown/release/provio_wasm.wasm"

# --- presets ---------------------------------------------------------------
python3 - "$STAGE/presets.js" <<'PY'
import json, os, re, sys

CR, LF = chr(13), chr(10)

def read(p):
    with open(p, encoding="utf-8", newline="") as f:
        return f.read().replace(CR + LF, LF)

blurb = {
    "starter.yaml": "Starter: what `provio init` writes (default allow + the floor + secrets guard)",
    "provio.yaml": "Full tour: four verdicts, fail-closed default",
    "ci.yaml": "Headless CI posture",
    "strict.yaml": "Default deny: allow-list only",
}
policies = [
    {"id": f"examples/{f}", "label": blurb[f], "kind": "example", "source": read(f"examples/{f}")}
    for f in ["starter.yaml", "provio.yaml", "ci.yaml", "strict.yaml"]
]
for d in sorted(os.listdir("packs")):
    p = f"packs/{d}/pack.yaml"
    if not os.path.exists(p):
        continue
    src = read(p)
    m = re.search(r"^description:\s*(.+)$", src, re.M)
    policies.append({"id": p, "label": m.group(1).strip() if m else d, "kind": "pack", "source": src})
presets = json.loads(read("crates/provio-wasm/presets/calls.json"))
dump = lambda v: json.dumps(v, indent=1, ensure_ascii=False)
out = [
    "// Generated by scripts/build_playground.sh from examples/*.yaml, packs/*/pack.yaml",
    "// and crates/provio-wasm/presets/calls.json. Do not edit by hand.",
    f"export const POLICY_PRESETS = {dump(policies)};",
    f"export const CALL_PRESETS = {dump(presets['calls'])};",
    f"export const SESSIONS = {dump(presets['sessions'])};",
    "",
]
with open(sys.argv[1], "w", encoding="utf-8", newline=LF) as f:
    f.write(LF.join(out))
PY

# --- publish / check ---------------------------------------------------------
FILES=(provio_wasm_bg.wasm provio_wasm.js presets.js)
mkdir -p "$OUT"
if [[ $CHECK == 1 ]]; then
  status=0
  for f in "${FILES[@]}"; do
    if ! cmp -s "$STAGE/$f" "$OUT/$f"; then
      echo "build_playground: $OUT/$f is stale — run scripts/build_playground.sh and commit the result" >&2
      status=1
    fi
  done
  [[ $status == 0 ]] && echo "build_playground: $OUT is up to date"
  exit $status
fi
for f in "${FILES[@]}"; do cp "$STAGE/$f" "$OUT/$f"; done
ls -l "${FILES[@]/#/$OUT/}"
echo "wasm gzip: $(gzip -9c "$OUT/provio_wasm_bg.wasm" | wc -c) bytes"
