#!/usr/bin/env python3
"""Generate the Homebrew formula and the Scoop manifest for a provio release
from its checksums.txt (the same prebuilt, signed binaries the installers
use).

    python scripts/gen_distribution.py v0.1.3 [--out packaging/dist]

Writes <out>/homebrew/provio.rb (for the writ-agent/homebrew-provio tap:
`brew install writ-agent/provio/provio`) and <out>/scoop/provio.json (for
the writ-agent/scoop-provio bucket: `scoop bucket add provio
https://github.com/writ-agent/scoop-provio; scoop install provio`).
"""

from __future__ import annotations

import json
import pathlib
import sys
import urllib.request

REPO = "writ-agent/provio"
DESC = "Safety floor for AI coding agents: one policy, checked before every tool call"
HOMEPAGE = "https://getprovio.vercel.app"


def checksums(tag: str) -> dict[str, str]:
    url = f"https://github.com/{REPO}/releases/download/{tag}/checksums.txt"
    with urllib.request.urlopen(url, timeout=60) as r:
        text = r.read().decode()
    out = {}
    for line in text.splitlines():
        parts = line.split()
        if len(parts) == 2:
            out[parts[1].lstrip("*")] = parts[0]
    return out


def formula(tag: str, sums: dict[str, str]) -> str:
    version = tag.lstrip("v")
    base = f"https://github.com/{REPO}/releases/download/{tag}"

    def asset(target: str) -> tuple[str, str]:
        name = f"provio-{target}"
        return f"{base}/{name}", sums[name]

    mac_arm, mac_arm_sha = asset("aarch64-apple-darwin")
    mac_x64, mac_x64_sha = asset("x86_64-apple-darwin")
    lin_arm, lin_arm_sha = asset("aarch64-unknown-linux-musl")
    lin_x64, lin_x64_sha = asset("x86_64-unknown-linux-musl")
    return f'''# Generated by scripts/gen_distribution.py in {REPO}; do not edit by hand.
class Provio < Formula
  desc "{DESC}"
  homepage "{HOMEPAGE}"
  version "{version}"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.arm?
      url "{mac_arm}"
      sha256 "{mac_arm_sha}"
    else
      url "{mac_x64}"
      sha256 "{mac_x64_sha}"
    end
  end

  on_linux do
    if Hardware::CPU.arm?
      url "{lin_arm}"
      sha256 "{lin_arm_sha}"
    else
      url "{lin_x64}"
      sha256 "{lin_x64_sha}"
    end
  end

  def install
    bin.install Dir["provio-*"].first => "provio"
  end

  test do
    assert_match version.to_s, shell_output("#{{bin}}/provio --version")
    (testpath/"provio.yaml").write <<~YAML
      version: 1
      default: allow
      packs: [floor]
    YAML
    system bin/"provio", "test", "cargo build"
    assert_match "floor-rm-home-or-root-denied", shell_output("#{{bin}}/provio test 'rm -rf ~'", 2)
  end
end
'''


def scoop(tag: str, sums: dict[str, str]) -> str:
    version = tag.lstrip("v")
    name = "provio-x86_64-pc-windows-msvc.exe"
    manifest = {
        "version": version,
        "description": DESC,
        "homepage": HOMEPAGE,
        "license": "Apache-2.0",
        "architecture": {
            "64bit": {
                "url": f"https://github.com/{REPO}/releases/download/{tag}/{name}#/provio.exe",
                "hash": sums[name],
            }
        },
        "bin": "provio.exe",
        "checkver": {"github": f"https://github.com/{REPO}"},
        "autoupdate": {
            "architecture": {
                "64bit": {
                    "url": f"https://github.com/{REPO}/releases/download/v$version/{name}#/provio.exe"
                }
            },
            "hash": {"url": f"https://github.com/{REPO}/releases/download/v$version/checksums.txt"},
        },
    }
    return json.dumps(manifest, indent=4) + "\n"


def main(argv: list[str]) -> None:
    if not argv or not argv[0].startswith("v"):
        sys.exit(__doc__)
    tag = argv[0]
    out = pathlib.Path(argv[argv.index("--out") + 1]) if "--out" in argv else pathlib.Path("packaging/dist")
    sums = checksums(tag)
    (out / "homebrew").mkdir(parents=True, exist_ok=True)
    (out / "scoop").mkdir(parents=True, exist_ok=True)
    (out / "homebrew" / "provio.rb").write_text(formula(tag, sums), encoding="utf-8")
    (out / "scoop" / "provio.json").write_text(scoop(tag, sums), encoding="utf-8")
    print(f"wrote {out}/homebrew/provio.rb and {out}/scoop/provio.json for {tag}")


if __name__ == "__main__":
    main(sys.argv[1:])
